GET http://localhost:4000/api/todos

### Get todo by id
GET http://localhost:4000/api/todos/2

###
POST http://localhost:4000/api/todos
# Authorization: Bearer accessToken
Content-Type: application/json

{
    "title": "Clean room",
    "description": "Clean room",
    "completed": false
}

###
DELETE  http://localhost:4000/api/todos/4

###
PATCH  http://localhost:4000/api/todos/5
Content-Type: application/json

{
    "title": "Clean room Update",
    "description": "Clean room",
    "completed": false
}